name: action_seg
channels:
  - defaults
dependencies:
  - python=3.9
  - pip
  - pip:
    - torch
    - torchvision
    - opencv-python
    - pandas
    - numpy
    - tqdm
    - scipy
    - pyyaml
    - matplotlib
    - scikit-learn
    - plotly
    - dash
    - pillow
